# Bubble sort

In VBA the [bubble sort](https://en.wikipedia.org/wiki/Bubble_sort) algorithm can be [written as](http://bettersolutions.com/vba/arrays/sorting-bubble-sort.htm):

```VB.NET
Sub BubbleSort(list()) 
'   Sorts an array using bubble sort algorithm
    Dim First As Integer, Last As Long 
    Dim i As Long, j As Long 
    Dim Temp As Long 
    
    First = LBound(list) 
    Last = UBound(list) 
    For i = First To Last - 1 
        For j = i + 1 To Last 
            If list(i) > list(j) Then 
                Temp = list(j) 
                list(j) = list(i) 
                list(i) = Temp 
            End If 
        Next j 
    Next i 
End Sub 
```

We can do a direct translation of this into Python:

In [1]:
def bubblesort(unsorted):
    """
    Sorts an array using bubble sort algorithm
    
    Paramters
    ---------
    
    unsorted : list
        The unsorted list
    
    Returns
    
    sorted : list
        The sorted list (in place)
    """
    
    last = len(unsorted)
    # All Python lists start from 0
    for i in range(last):
        for j in range(i+1, last):
            if unsorted[i] > unsorted[j]:
                temp = unsorted[j]
                unsorted[j] = unsorted[i]
                unsorted[i] = temp
    return unsorted

In [2]:
unsorted = [2, 4, 6, 0, 1, 3, 5]
print(bubblesort(unsorted))

[0, 1, 2, 3, 4, 5, 6]


By comparing the two codes we can see the essential changes needed:

* Python does not declare the type of the variables; the `DIM` statements are not needed.
* There is nothing special about lists or arrays as variables when passed as arguments.
* To define functions the keyword is `def` instead of `Sub`.
* To define the start of a block (the body of a function, or a loop, or a conditional) a colon `:` is used.
* To define the block itself, indentation is used. The block ends when the code indentation ends.
* Comments are either enclosed in quotes `"` as for the docstring, or using `#`.
* The return value(s) from a function use the keyword `return`, not the name of the function.
* Accessing arrays uses square brackets, not round.
* The function `range` produces a range of integers, usually used to loop over.

Note: there are in-built Python functions to sort lists which should be used in general:

In [3]:
unsorted = [2, 4, 6, 0, 1, 3, 5]
print(sorted(unsorted))

[0, 1, 2, 3, 4, 5, 6]


Note: there is a "more Pythonic" way of writing the bubble sort function, taking advantage of the feature that Python can assign to multiple things at once. Compare the internals of the loop:

In [4]:
def bubblesort(unsorted):
    """
    Sorts an array using bubble sort algorithm
    
    Paramters
    ---------
    
    unsorted : list
        The unsorted list
    
    Returns
    
    sorted : list
        The sorted list (in place)
    """
    
    last = len(unsorted)
    # All Python lists start from 0
    for i in range(last):
        for j in range(i+1, last):
            if unsorted[i] > unsorted[j]:
                unsorted[j], unsorted[i] = unsorted[i], unsorted[j]
    return unsorted

In [5]:
unsorted = [2, 4, 6, 0, 1, 3, 5]
print(bubblesort(unsorted))

[0, 1, 2, 3, 4, 5, 6]


This gets rid of the need for a temporary variable.

## Exercise

Here is a [VBA code](http://bettersolutions.com/vba/arrays/sorting-counting-sort.htm) for the [counting sort](https://en.wikipedia.org/wiki/Counting_sort) algorithm:

```VB.NET
Sub Countingsort(list) 
    Dim counts() As Long 
    Dim i As Long 
    Dim j As Long 
    Dim next_index As Long 
    Dim min, max 
    Dim min_value As Variant, max_value As Variant 

'   Allocate the counts array. VBA automatically
'   initialises all entries to 0.

    min_value = Minimum(list) 
    max_value = Maximum(list) 
    
    min = LBound(list) 
    max = UBound(list) 
    
    ReDim counts(min_value To max_value) 
    
    ' Count the values.
    For i = min To max 
        counts(list(i)) = counts(list(i)) + 1 
    Next i 

    ' Write the items back into the list array.
    next_index = min 
    For i = min_value To max_value 
        For j = 1 To counts(i) 
            list(next_index) = i 
            next_index = next_index + 1 
        Next j 
    Next i 
End Sub 

Private Function Maximum(l) 
    Dim s1, s2 
    Dim i 
    s1 = LBound(l) 
    s2 = UBound(l) 
    Maximum = l(s1) 
    For i = s1 To s2 
        If l(i) > Maximum Then Maximum = l(i) 
    Next i 
End Function 

Private Function Minimum(l) 
    Dim s1, s2 
    Dim i 
    s1 = LBound(l) 
    s2 = UBound(l) 
    Minimum = l(s1) 
    For i = s1 To s2 
        If l(i) < Minimum Then Minimum = l(i) 
    Next i 
End Function 
```

Translate this into Python. Note that the in-built Python `min` and `max` functions can be used on lists in place of the `Minimum` and `Maximum` functions above. To create a list of the correct size you can use

```python
    counts = list(range(min_value, max_value+1))
```

but this list will not contain zeros so must be reset.

In [6]:
def countingsort(unsorted):
    """
    Sorts an array using counting sort algorithm
    
    Paramters
    ---------
    
    unsorted : list
        The unsorted list
    
    Returns
    
    sorted : list
        The sorted list (in place)
    """
    # Allocate the counts array
    min_value = min(unsorted)
    max_value = max(unsorted)
    # This creates a list of the right length, but the entries are not zero, so reset
    counts = list(range(min_value, max_value+1))
    for i in range(len(counts)):
        counts[i] = 0
    # Count the values
    last = len(unsorted)
    for i in range(last):
        counts[unsorted[i]] += 1
    # Write the items back into the list array
    next_index = 0
    for i in range(min_value, max_value+1):
        for j in range(counts[i]):
            unsorted[next_index] = i
            next_index += 1
    
    return unsorted

In [7]:
unsorted = [2, 4, 6, 0, 1, 3, 5]
print(countingsort(unsorted))

[0, 1, 2, 3, 4, 5, 6]


# Simplex Method

For the linear programming problem
$$
\begin{align}
  \max x_1 + x_2 &= z \\
  2 x_1 + x_2 & \le 4 \\
  x_1 + 2 x_2 & \le 3
\end{align}
$$
where $x_1, x_2 \ge 0$, one standard approach is the [simplex method](https://en.wikipedia.org/wiki/Simplex_algorithm).

Introducing slack variables $s_1, s_2 \ge 0$ the standard tableau form becomes
$$
\begin{pmatrix}
  1 & -1 & -1 & 0 & 0 \\
  0 & 2 & 1 & 1 & 0 \\
  0 & 1 & 2 & 0 & 1 
\end{pmatrix}
\begin{pmatrix}
  z & x_1 & x_2 & s_1 & s_2
\end{pmatrix}^T = \begin{pmatrix} 0 \\ 4 \\ 3 \end{pmatrix}.
$$

The simplex method performs row operations to remove all negative numbers from the top row, at each stage choosing the smallest (in magnitude) pivot.

Assume the tableau is given in this standard form. We can use `numpy` to implement the problem.

In [1]:
import numpy

In [21]:
tableau = numpy.array([ [1, -1, -1, 0, 0, 0], 
                        [0,  2,  1, 1, 0, 4],
                        [0,  1,  2, 0, 1, 3] ], dtype=numpy.float64)
print(tableau)

[[ 1. -1. -1.  0.  0.  0.]
 [ 0.  2.  1.  1.  0.  4.]
 [ 0.  1.  2.  0.  1.  3.]]


To access an entry we use square brackets as with lists:

In [22]:
print(tableau[0, 0])
print(tableau[1, 2])
row = 2
column = 5
print(tableau[row, column])

1.0
1.0
3.0


To access a complete row or column, we use slicing notation:

In [23]:
print(tableau[row, :])
print(tableau[:, column])

[ 0.  1.  2.  0.  1.  3.]
[ 0.  4.  3.]


To apply the simplex method, we have to remove the negative entries in row `0`. These appear in columns `1` and `2`. For column `1` the pivot in row `1` has magnitude $|-1/2| = 1/2$ and the pivot in row `2` has magnitude $|-1/1|=1$. So we choose row `1`.

To perform the row operation we want to eliminate all entries in column `1` except for the diagonal, which is set to $1$:

In [24]:
column = 1
pivot_row = 1
# Rescale pivot row
tableau[pivot_row, :] /= tableau[pivot_row, column]
# Remove all entries in columns except the pivot
pivot0 = tableau[0, column] / tableau[pivot_row, column]
tableau[0, :] -= pivot0 * tableau[pivot_row, :]
pivot2 = tableau[2, column] / tableau[pivot_row, column]
tableau[2, :] -= pivot2 * tableau[pivot_row, :]

print(tableau)

[[ 1.   0.  -0.5  0.5  0.   2. ]
 [ 0.   1.   0.5  0.5  0.   2. ]
 [ 0.   0.   1.5 -0.5  1.   1. ]]


Now we repeat this on column `2`, noting that we can only pivot on row `2`:

In [25]:
column = 2
pivot_row = 2
# Rescale pivot row
tableau[pivot_row, :] /= tableau[pivot_row, column]
# Remove all entries in columns except the pivot
pivot0 = tableau[0, column] / tableau[pivot_row, column]
tableau[0, :] -= pivot0 * tableau[pivot_row, :]
pivot1 = tableau[1, column] / tableau[pivot_row, column]
tableau[1, :] -= pivot1 * tableau[pivot_row, :]

print(tableau)

[[ 1.          0.          0.          0.33333333  0.33333333  2.33333333]
 [ 0.          1.          0.          0.66666667 -0.33333333  1.66666667]
 [ 0.          0.          1.         -0.33333333  0.66666667  0.66666667]]


We read off the solution: $z = 7/3$ when $x_1 = 5/3$ and $x_2 = 2/3$:

In [26]:
print("z =", tableau[0, -1])
print("x_1 =", tableau[1, -1])
print("x_2 =", tableau[2, -1])

z = 2.33333333333
x_1 = 1.66666666667
x_2 = 0.666666666667


Let's turn that into a function.

In [44]:
def simplex(tableau):
    """
    Assuming a standard form tableau, find the solution
    """
    nvars = tableau.shape[1] - tableau.shape[0] - 1
    for column in range(1, nvars+2):
        if tableau[0, column] < 0:
            pivot_row = numpy.argmin(numpy.abs(tableau[0, column] / tableau[1:, column])) + 1
            # Rescale pivot row
            tableau[pivot_row, :] /= tableau[pivot_row, column]
            # Remove all entries in columns except the pivot
            for row in range(0, pivot_row):
                pivot = tableau[row, column] / tableau[pivot_row, column]
                tableau[row, :] -= pivot * tableau[pivot_row, :]
            for row in range(pivot_row+1, tableau.shape[0]):
                pivot = tableau[row, column] / tableau[pivot_row, column]
                tableau[row, :] -= pivot * tableau[pivot_row, :]
    z = tableau[0, -1]
    x = tableau[1:nvars+1, -1]
    return z, x

In [46]:
tableau = numpy.array([ [1, -1, -1, 0, 0, 0], 
                        [0,  2,  1, 1, 0, 4],
                        [0,  1,  2, 0, 1, 3] ], dtype=numpy.float64)
z, x = simplex(tableau)
print("z =", z)
print("x =", x)

z = 2.33333333333
x = [ 1.66666667  0.66666667]


## Building the tableau

Once the problem is phrased in the tableau form the short `simplex` function solves it without problem. However, for large problems, we don't want to type in the matrix by hand. Instead we want a way of keeping track of the objective function to maximize, and the constraints, and make the computer do all the work.

To do that we'll introduce *classes*. In VBA a class is a special module, and you access its variables and methods using dot notation. For example, if `Student` is a class, which has a variable `Name`, and `s1` is a `Student` object, then `s1.Name` is the name associated with that particular instance of student.

The same approach is used in Python:

In [49]:
class Student(object):
    
    def __init__(self, name):
        self.name = name
        
    def print_name(self):
        print("Hello", self.name)

In [51]:
s1 = Student("Ian Hawke")
print(s1.name)
s2 = Student("Jörg Fliege")
s2.print_name()

Ian Hawke
Hello Jörg Fliege


See how this compares to VBA.

* The `class` keyword is used to start the definition of the class.
* The name of the class (`Student`) is given. It follows similar rules and conventions to variables, but typically is capitalized.
* The name in brackets (`object`) is what the class *inherits* from. Here we use the default (`object`).
* The colon and indentation denotes the class definition, in the same way as we've seen for functions and loops.
* Functions defined inside the class are *methods*. The first argument will always be an instance of the class, and by convention is called `self`. Methods are called using `<instance>.<method>`.
* When an instance is created (eg, by `s1 = Student(...)`) the `__init__` method is called if it exists. We can use this to set up the instance.

There are a number of special methods that can be defined that work with Python operations. For example, suppose we printed the instances above:

In [52]:
print(s1)
print(s2)

This isn't very informative. However, we can define the *string representation* of our class using the `__repr__` method:

In [57]:
class Student(object):
    
    def __init__(self, name):
        self.name = name
        
    def __repr__(self):
        return self.name

In [58]:
s1 = Student("Ian Hawke")
s2 = Student("Jörg Fliege")
print(s1)
print(s2)

Ian Hawke
Jörg Fliege


We can also define what it means to add two instances of our class:

In [59]:
class Student(object):
    
    def __init__(self, name):
        self.name = name
        
    def __repr__(self):
        return self.name
    
    def __add__(self, other):
        return Student(self.name + " and " + other.name)

In [60]:
s1 = Student("Ian Hawke")
s2 = Student("Jörg Fliege")
print(s1 + s2)

Ian Hawke and Jörg Fliege


Going back to the simplex method, we want to define a class that contains the objective function and the constraints, a method to solve the problem, and a representation of the problem and solution.

In [70]:
class Constraint(object):
    def __init__(self, coefficients, gtlteq, value):
        self.coefficients = numpy.array(coefficients)
        self.gtlteq = gtlteq
        self.value = value
        
    def __repr__(self):
        string = ""
        for i in range(len(self.coefficients)-1):
            string += str(self.coefficients[i]) + " x_{}".format(i+1) + " + "
        string += str(self.coefficients[-1]) + " x_{}".format(len(self.coefficients))
        string += " " + self.gtlteq + " "
        string += str(self.value)
        return string

In [71]:
c1 = Constraint([2, 1], "le", 4)
c2 = Constraint([1, 2], "le", 3)
print(c1)
print(c2)

2 x_1 + 1 x_2 le 4
1 x_1 + 2 x_2 le 3


In [86]:
class Linearprog(object):
    
    def __init__(self, objective):
        self.objective = numpy.array(objective)
        self.constraints = []
        self.tableau = numpy.array([1.0])
        self.tableau = numpy.hstack((self.tableau, -self.objective))
        self.tableau = numpy.reshape(self.tableau, (1, len(self.tableau)))
        self.tableau_rhs = numpy.array([0.0])
        
    def add_constraint(self, constraint):
        self.constraints.append(constraint)
        print(self.tableau)
        print(numpy.zeros((self.tableau.shape[0], 1)))
        self.tableau = numpy.hstack((self.tableau, numpy.zeros((self.tableau.shape[0], 1))))
        new_row = numpy.zeros_like(self.tableau[0, :])
        row_number = self.tableau.shape[1]+1
        new_row[1:2+len(self.objective)] = constraint.coefficients
        if constraint.gtlteq == "le":
            new_row[row_number] = 1.0
        elif constraint.gtlteq == "ge":
            new_row[row_number] = -1.0
        # Anything else counts as "="
        self.tableau = numpy.vstack((self.tableau, new_row))
        self.tableau_rhs = numpy.vstack((self.tableau_rhs, constraint.value))
        
    def simplex(self):
       pass

    def __repr__(self):
        string = "max "
        for i in range(len(self.objective)-1):
            string += str(self.objective[i]) + " x_{}".format(i+1) + " + "
        string += str(self.objective[-1]) + " x_{}".format(len(self.objective))
        string += "\n\nwith constraints\n"
        for c in constraints:
            string += c.__repr__()
        return string

In [87]:
problem = Linearprog([1, 1])
problem.add_constraint(c1)
problem.add_constraint(c2)
print(problem)

[[ 1. -1. -1.]]
[[ 0.]]


ValueError: could not broadcast input array from shape (2) into shape (3)